// Package cfg: INI 解析。
//
// 极简 INI 解析器，只支持：
//   - [section] 头
//   - key = value（空格 trim）
//   - ; 或 # 开头 = 注释
//   - 空行
//   - value 可用 "..." 或 '...' 引号包裹（首尾匹配才剥）
//
// 不支持：嵌套 section、include、escape 字符、多行 value。
// 这对 smith.ini 这种 12 字段的小配置文件够用。
//
// v1-L1 契约：所有 API 返 (T, error)。缺字段用零值（ini 文件没该 section 不报错）。

package cfg

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// 默认值（PLAN §0.6 B6 字段表 + B7 字段约定）
const (
	DefaultKeyFile   = "smith.key"
	DefaultVision    = false
	DefaultTimeout   = 120
	DefaultConfirm   = true
	DefaultMaxTurns  = 10
	DefaultImgHistory = 2
	DefaultFontSize  = 12
)

// Config 是 smith.ini 解析后的根结构。
type Config struct {
	LLM   LLMConfig
	Agent AgentConfig
	UI    UIConfig
	path  string
}

// LLMConfig 是 [llm] 段。
type LLMConfig struct {
	Base     string
	Model    string
	KeyFile  string
	Key      string
	Provider string // "openai" | "anthropic" | "deepseek"；空 = openai
	Vision   bool
	Timeout  int
}

// AgentConfig 是 [agent] 段。
type AgentConfig struct {
	Confirm    bool
	Whitelist  []string
	MaxTurns   int
	ImgHistory int
}

// UIConfig 是 [ui] 段。
type UIConfig struct {
	Font     string
	FontSize int
}

// 错误集
var (
	ErrFileNotFound = errors.New("cfg: file not found")
	ErrNoEquals     = errors.New("cfg: key=value expected")
	ErrInvalidBool  = errors.New("cfg: invalid bool")
	ErrInvalidInt   = errors.New("cfg: invalid int")
)

// Default 返一个默认 cfg（无 ini 路径）。主程序在找不到 ini 时用它启动。
func Default() *Config {
	return defaultConfig()
}

// Load 从 path 加载 INI 文件并解析。文件不存在返 ErrFileNotFound。
// 任何 [section] 缺失 = 用该段默认值。
func Load(path string) (*Config, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrFileNotFound, err)
	}
	defer f.Close()
	c := defaultConfig()
	c.path = path
	sc := bufio.NewScanner(f)
	section := ""
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, ";") || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(strings.TrimSpace(line[1 : len(line)-1]))
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			return nil, fmt.Errorf("%w at line %d: %q", ErrNoEquals, lineNo, line)
		}
		key := strings.TrimSpace(line[:eq])
		val := unquote(strings.TrimSpace(line[eq+1:]))
		if err := setField(c, section, key, val); err != nil {
			return nil, fmt.Errorf("line %d [%s] %s: %w", lineNo, section, key, err)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("cfg: scan: %w", err)
	}
	return c, nil
}

// Path 返回配置文件路径（Load 时设）。
func (c *Config) Path() string {
	return c.path
}

// Save 把 Config 写回 path（INI 格式，UTF-8 无 BOM）。
//
// 行为：
//   - 文件不存在 → 创建
//   - 文件存在 → 覆盖 [llm] 段，其它段保持原样（writeWhole=true 时整文件覆盖）
//   - 不写 [llm] key 字段（key 应该走 keyfile = smith.key 单文件路径，
//     避免 ini 里留明文 key）—— 除非 explicitly asked
//
// L1 硬规则：返 (error)。L5：不吞错。
func Save(path string, c *Config, writeWhole bool) error {
	if path == "" {
		return errors.New("cfg: save path empty")
	}
	if c == nil {
		return errors.New("cfg: nil config")
	}
	if writeWhole {
		return os.WriteFile(path, []byte(renderINI(c)), 0644)
	}
	// merge 模式：保留其它段，只覆盖 [llm]
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("cfg: read existing %s: %w", path, err)
	}
	merged := mergeLLMSection(string(existing), c)
	return os.WriteFile(path, []byte(merged), 0644)
}

// renderINI 整个 Config 序列化为 INI 文本（首次写入用）。
func renderINI(c *Config) string {
	var b strings.Builder
	b.WriteString("; smith.ini - generated by first-run dialog\n\n")
	writeLLMSection(&b, c)
	if c.Agent.Confirm || c.Agent.MaxTurns != DefaultMaxTurns || c.Agent.ImgHistory != DefaultImgHistory || len(c.Agent.Whitelist) > 0 {
		b.WriteString("\n[agent]\n")
		if c.Agent.Confirm {
			b.WriteString("confirm = 1\n")
		} else {
			b.WriteString("confirm = 0\n")
		}
		if c.Agent.MaxTurns != 0 && c.Agent.MaxTurns != DefaultMaxTurns {
			fmt.Fprintf(&b, "maxturns = %d\n", c.Agent.MaxTurns)
		}
		if c.Agent.ImgHistory != 0 && c.Agent.ImgHistory != DefaultImgHistory {
			fmt.Fprintf(&b, "imghistory = %d\n", c.Agent.ImgHistory)
		}
		if len(c.Agent.Whitelist) > 0 {
			fmt.Fprintf(&b, "whitelist = %s\n", strings.Join(c.Agent.Whitelist, ", "))
		}
	}
	if c.UI.Font != "" || c.UI.FontSize != 0 && c.UI.FontSize != DefaultFontSize {
		b.WriteString("\n[ui]\n")
		if c.UI.Font != "" {
			fmt.Fprintf(&b, "font = %s\n", c.UI.Font)
		}
		if c.UI.FontSize != 0 && c.UI.FontSize != DefaultFontSize {
			fmt.Fprintf(&b, "fontsize = %d\n", c.UI.FontSize)
		}
	}
	return b.String()
}

// writeLLMSection 写 [llm] 段（不写 key，key 走 smith.key）。
func writeLLMSection(b *strings.Builder, c *Config) {
	b.WriteString("[llm]\n")
	if c.LLM.Base != "" {
		fmt.Fprintf(b, "base = %s\n", c.LLM.Base)
	}
	if c.LLM.Model != "" {
		fmt.Fprintf(b, "model = %s\n", c.LLM.Model)
	}
	if c.LLM.Provider != "" {
		fmt.Fprintf(b, "provider = %s\n", c.LLM.Provider)
	}
	if c.LLM.KeyFile != "" {
		fmt.Fprintf(b, "keyfile = %s\n", c.LLM.KeyFile)
	}
	if c.LLM.Timeout != 0 && c.LLM.Timeout != DefaultTimeout {
		fmt.Fprintf(b, "timeout = %d\n", c.LLM.Timeout)
	}
	if c.LLM.Vision {
		b.WriteString("vision = 1\n")
	}
}

// mergeLLMSection 把 c.LLM 合并进 existing，替换/插入 [llm] 段，其它段不动。
//
// 策略：按行扫描，遇到 [llm] 段头就丢弃该段所有行直到下一个段头；遇到
// [llm] 时在原地插入新写的 [llm] 段。如果文件从头到尾都没有 [llm]，
// 末尾追加。每行后都写 \n（除最后一行）。
func mergeLLMSection(existing string, c *Config) string {
	lines := strings.Split(existing, "\n")
	var out strings.Builder
	inLLM := false
	wroteLLM := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		isSectionHeader := strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]")

		if isSectionHeader {
			inLLM = false // 任何段头都关闭 [llm] 状态
		}

		if isSectionHeader && strings.EqualFold(trimmed, "[llm]") {
			// 在原地插入新 [llm] 段
			if !wroteLLM {
				writeLLMSection(&out, c)
				wroteLLM = true
			}
			inLLM = true // 标记吞掉原段
			// 段头本身不写
			if i < len(lines)-1 {
				out.WriteString("\n")
			}
			continue
		}

		if inLLM {
			// 在原 [llm] 段内 → 跳过（但行末 \n 要补回，否则下一行会粘）
			if i < len(lines)-1 {
				out.WriteString("\n")
			}
			continue
		}

		// 普通行 / 注释 / 非 [llm] 段头 → 原样输出
		out.WriteString(line)
		if i < len(lines)-1 {
			out.WriteString("\n")
		}
	}

	// 文件没 [llm] 段 → 在末尾追加（前面行已带 \n）
	if !wroteLLM {
		writeLLMSection(&out, c)
	}
	return out.String()
}

func defaultConfig() *Config {
	return &Config{
		LLM: LLMConfig{
			KeyFile: DefaultKeyFile,
			Vision:  DefaultVision,
			Timeout: DefaultTimeout,
		},
		Agent: AgentConfig{
			Confirm:    DefaultConfirm,
			MaxTurns:   DefaultMaxTurns,
			ImgHistory: DefaultImgHistory,
		},
		UI: UIConfig{
			FontSize: DefaultFontSize,
		},
	}
}

func setField(c *Config, section, key, val string) error {
	switch section {
	case "llm":
		return setLLM(&c.LLM, key, val)
	case "agent":
		return setAgent(&c.Agent, key, val)
	case "ui":
		return setUI(&c.UI, key, val)
	case "":
		// 顶层 key 暂忽略（未来可作 [default] 段）
		return nil
	default:
		// 未知 section 静默忽略（避免 1 个拼写错误毁整个启动）
		return nil
	}
}

func setLLM(c *LLMConfig, key, val string) error {
	switch strings.ToLower(key) {
	case "base":
		c.Base = val
	case "model":
		c.Model = val
	case "keyfile":
		c.KeyFile = val
	case "key":
		c.Key = val
	case "provider":
		c.Provider = strings.ToLower(val)
	case "vision":
		b, err := parseBool(val)
		if err != nil {
			return err
		}
		c.Vision = b
	case "timeout":
		n, err := parseInt(val)
		if err != nil {
			return err
		}
		c.Timeout = n
	default:
		return nil
	}
	return nil
}

func setAgent(c *AgentConfig, key, val string) error {
	switch strings.ToLower(key) {
	case "confirm":
		b, err := parseBool(val)
		if err != nil {
			return err
		}
		c.Confirm = b
	case "whitelist":
		c.Whitelist = splitList(val)
	case "maxturns":
		n, err := parseInt(val)
		if err != nil {
			return err
		}
		c.MaxTurns = n
	case "imghistory":
		n, err := parseInt(val)
		if err != nil {
			return err
		}
		c.ImgHistory = n
	default:
		return nil
	}
	return nil
}

func setUI(c *UIConfig, key, val string) error {
	switch strings.ToLower(key) {
	case "font":
		c.Font = val
	case "fontsize":
		n, err := parseInt(val)
		if err != nil {
			return err
		}
		c.FontSize = n
	default:
		return nil
	}
	return nil
}

func parseBool(s string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "true", "yes", "on":
		return true, nil
	case "0", "false", "no", "off", "":
		return false, nil
	default:
		return false, fmt.Errorf("%w: %q", ErrInvalidBool, s)
	}
}

func parseInt(s string) (int, error) {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		return 0, fmt.Errorf("%w: %q (%v)", ErrInvalidInt, s, err)
	}
	return n, nil
}

func splitList(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func unquote(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}
